networks:
  monitoring:
    driver: bridge

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.6.0
    user: "1000:1000"
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config/rules:/etc/prometheus/rules/
    ports:
      - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    - --web.external-url=https://9090-${WEB_HOST}
    networks:
      - monitoring

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.9.1
    volumes:
      - '/proc:/host/proc:ro'
      - '/sys:/host/sys:ro'
      - '/:/rootfs:ro'
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitoring

  app-demo-1:
    container_name: app-demo-1
    image: julius/prometheus-demo-service:0.12.0
    ports:
      - "10001:8080"
    networks:
      - monitoring

  app-demo-2:
    container_name: app-demo-2
    image: julius/prometheus-demo-service:0.12.0
    ports:
      - "10002:8080"
    networks:
      - monitoring

  app-demo-3:
    container_name: app-demo-3
    image: julius/prometheus-demo-service:0.12.0
    ports:
      - "10003:8080"
    networks:
      - monitoring

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.28.1
    user: "1000:1000"
    ports:
      - 9093:9093
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
      - --web.external-url=https://9093-${WEB_HOST}
      - --log.level=debug
    volumes:
      - ./alertmanager/data:/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:v0.27.0
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:12.3.0-18081912450-ubuntu
    user: "1000:1000"
    # ports:
    #   - 3000:3000
    environment:
      GF_SERVER_DOMAIN: 9000-${WEB_HOST}
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/config/:/etc/grafana/
    networks:
      - monitoring

  nginx:
    container_name: nginx
    image: nginx:1.29.1-alpine-slim
    ports:
      - 9000:80
    environment:
      SERVER_DOMAIN: 9000-${WEB_HOST}
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - grafana
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx-exporter
    ports:
      - 9113:9113
    command:
      - '-nginx.scrape-uri=http://nginx/stub_status'
    depends_on:
      - nginx
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    privileged: true
    ports:
      - 8888:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  mysql:
    image: mysql:9.4.0-oraclelinux9
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - monitoring

  mysql-exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: mysql-exporter
    command:
      - "--mysqld.username=root"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    environment:
      MYSQLD_EXPORTER_PASSWORD: rootpass
    depends_on:
      - mysql
    networks:
      - monitoring

  mariadb-slap:
    image: mariadb:12.0.2-noble
    container_name: mariadb-slap
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    command:
      - /bin/bash
      - -c
      - |
        mariadb-slap -h mysql --skip-ssl -p$${MYSQL_ROOT_PASSWORD} --auto-generate-sql -vv --iterations=10
    depends_on:
      - mysql
    restart: always
    networks:
      - monitoring
