# Alerting rules exist in a rule group. Rules within a group are run sequentially at a evaluation time.
groups:
- name: node-exporter-alerts
  rules:
  - alert: NodeExporterDown
    # Query up with label job="node-exporter" to see if it down or not
    expr: up{job="node-exporter"} == 0
    # Wait before firing alert for 1 minute
    for: 1m
- name: node-exporter-alerts-label
  rules:
  # Rule to alert when node-exporter is down for 30 seconds
  - alert: NodeExporterDown30Secs
    expr: up{job="node-exporter"} == 0
    for: 30s
    # Set label service name and severity warning to alert
    labels:
      service: node-exporter
      severity: warning
  # Rule to alert when node-exporter is down for a minute
  - alert: NodeExporterDown1Min
    expr: up{job="node-exporter"} == 0
    for: 1m
    # Set label service name and severity critical to alert
    labels:
      service: node-exporter
      severity: critical
  - alert: ssl-expired-alerts
    expr: (probe_ssl_earliest_cert_expiry{job="blackbox-probe", instance="https://git.demo.opsta.co.th"} - time()) / 86400 < 30
  - alert: app-demo-alerts
    expr: (probe_success != 1) or (probe_http_duration_seconds > 1)

- name: mysqld_rules
  rules:
  # Record slave lag seconds for pre-computed timeseries that takes
  # `mysql_slave_status_sql_delay` into account
  - record: instance:mysql_slave_lag_seconds
    expr: mysql_slave_status_seconds_behind_master - mysql_slave_status_sql_delay
  # Record slave lag via heartbeat method
  - record: instance:mysql_heartbeat_lag_seconds
    expr: mysql_heartbeat_now_timestamp_seconds - mysql_heartbeat_stored_timestamp_seconds
  - record: job:mysql_transactions:rate5m
    expr: sum without (command) (rate(mysql_global_status_commands_total{command=~"(commit|rollback)"}[5m]))

- name: MySQLdAlerts
  rules:
  - alert: MySQLDown
    expr: mysql_up != 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'MySQL {{$labels.job}} on {{$labels.instance}} is not up.'
      summary: MySQL not up.
