{
 "title": "Application RED with Logs Copy (Better Version)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(training_response_total{job=\"app-prom\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(training_http_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(training_response_total{code!~\"2.*|3.*\", instance=\"$instance\"}) by(path) / sum(training_response_total{instance=\"$instance\"}) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(training_http_request_duration_seconds_count{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "PR95 {{path}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\", container=\"$instance\"} | logfmt",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Application Failed Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\", container=\"$instance\"} |= \"failed\" | logfmt",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Failed Logs Statistic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({job=\"docker\", container=\"$instance\"} |= \"failed\")[$__range]))"
    }
   ]
  },
  {
   "title": "Error Rate from logs",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job=\"docker\",container=\"$instance\"} | logfmt | level=~\"warning|error\" [$__range])) by (path) / sum(count_over_time({job=\"docker\",container=\"$instance\"} | logfmt [$__range])) by (path)",
     "legendFormat": "{{$path}}"
    }
   ]
  },
  {
   "title": "Application Failed Logs from logfmt",
   "type": "logs",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\", container=\"$instance\"} | logfmt | level=~\"error|warning\"",
     "maxLines": 100
    }
   ]
  },
  {
   "title": "Failed Logs Statistic from logfmt",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({job=\"docker\", container=\"$instance\"} | logfmt | level=~\"error|warning\")[$__range]))"
    }
   ]
  }
 ]
}