{
 "title": "Container Log",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   { "name": "search", "label": "Search" },
   { "name": "status", "label": "Status" }
  ]
 },
 "panels": [
  {
   "title": "Status Statistic",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({hostname=~\"$hostname\", container=~\"$container\"} | pattern `<ip> - <_> [<timestamp>] \"<method> <uri> <http>\" <status> <size> \"<referrer>\" \"<agent>\"`)[$__range])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "count all status code that is 4xx and 5xx and use red color for all data",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time(({job=\"docker\", hostname=~\"$hostname\", container=~\"$container\"} | pattern `<ip> - <_> [<timestamp>] \"<method> <uri> <http>\" <status> <size> \"<referrer>\" \"<agent>\"` | status>=400 | status<600)[$__range]))"
    }
   ]
  },
  {
   "title": "All Logs Distribution",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container) (count_over_time({job=\"docker\", hostname=~\"$hostname\"} | pattern `<ip> - <_> [<timestamp>] \"<method> <uri> <http>\" <status> <size> \"<referrer>\" \"<agent>\"` | status=~\"$status\" |~ `$search` [$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Selected Logs Distribution",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (container) (count_over_time({job=\"docker\", hostname=~\"$hostname\", container=~\"$container\"} | pattern `<ip> - <_> [<timestamp>] \"<method> <uri> <http>\" <status> <size> \"<referrer>\" \"<agent>\"` | status=~\"$status\" |~ `$search` [$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"docker\", hostname=~\"$hostname\", container=~\"$container\"} |~ `$search` \n| logfmt \n| pattern `<ip> - <_> [<timestamp>] \"<method> <uri> <http>\" <status> <size> \"<referrer>\" \"<agent>\"` \n| status=~\"$status\"",
     "maxLines": 100
    }
   ]
  }
 ]
}