{
 "title": "System Log",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Datasource", "query": "loki" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {}
   },
   {
    "name": "filename",
    "label": "Filename",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "All Logs Distribution",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (filename) (count_over_time({job=\"varlogs\", hostname=\"$hostname\"} |= `$search` [$__interval]))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Selected Logs Distribution",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (filename) (count_over_time({job=\"varlogs\", hostname=~\"$hostname\", filename=~\"$filename\"} |= `$search` [$__interval]))",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"varlogs\", filename=~\"$filename\", hostname=~\"$hostname\"} |= `$search` | logfmt",
     "maxLines": 100
    }
   ]
  }
 ]
}