apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

# Adding datasources to Grafana
datasources:
  # Prometheus datasources
  - uid: prometheus
    orgId: 1
    name: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    # Custom datasource configuration
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.50.1
