apiVersion: 1

# Mark provisioned data sources for deletion if they are no longer in a provisioning file.
# It takes no effect if data sources are already listed in the deleteDatasources section.
prune: true

# Adding datasources to Grafana
datasources:
  # Prometheus datasources
  - uid: prometheus
    orgId: 1
    name: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    # Custom datasource configuration
    jsonData:
      prometheusType: Prometheus
      prometheusVersion: 2.50.1
  # Loki datasources
  - uid: loki
    orgId: 1
    name: loki
    type: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: '"trace_id": "([A-Za-z0-9]+)", "span_id"'
          name: HotRod
          url: $${__value.raw}
  # Jaeger datasources
  - uid: jaeger
    orgId: 1
    name: jaeger
    type: jaeger
    url: http://jaeger:16686
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        customQuery: true
        datasourceUid: loki
        query: '{container=~"$${__span.tags["host.name"]}"} |~ "$${__span.traceId}" |~ "$${__span.spanId}"'
